version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9  # Install Python 3.9 on the environment
   
    
  pre_build:
    commands:
      - echo === CHECK IF PYTHON AND AWSCLI WAS INSTALLED SUCCESSFULLY ===
      - python3 --version  # Verify if Python version 3.9 was installed
      - aws --version      # Verify if AWSCLI is installed

    
  build: # Run Your CODE
    commands:
      - echo === RUN YOUR CODE HERE ===
      - python3 my_app.py # RUN A PYTHON CODE
    
    
  post_build:
    commands:
      - echo === THIS IS MY POST BUILD SECTION ===
      - echo === Build is completed at `date`...  # Notify the user the build is complete with date timestamp


artifacts:
  files:
    - '**/*' # Grab all files and zip them
    name: builtartifact-for-2stage-build-$(date +%Y-%m-%d)

